workflows:
  my-workflow:
    name: Default
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      # vars:
      #   PUBLIC_ENV_VAR: "value here"
      flutter: beta
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
        - ~/Library/Caches/CocoaPods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'build'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
       - name: Android
         script: flutter build apk --release --split-per-abi
       - name: Ios
         script: flutter build ios --debug --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/**
      # - build/linux/**/**
      - build/ios/ipa/*.ipa
    # publishing:
    #   email:
    #     recipients:
    #       - name@example.com
    #   scripts:
    #     - echo 'Post-publish script'