name: Build
on: [push]
jobs:
  build:
    name: Build
    if: "contains(github.event.head_commit.message, 'ci')"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "15.0.2"
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Getting dependencies
        run: flutter pub get
      - name: Test stage
        run: flutter test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
      - name: Build application for android.
        run: flutter build apk --split-per-abi
      # - run: flutter build ios --release --no-codesign
      - name: Archive apk-arm64
        uses: actions/upload-artifact@v2
        with:
          name: exyji-arm64-v8a.apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - name: Archive apk-v7
        uses: actions/upload-artifact@v2
        with:
          name: exyji-armeabi-v7a.apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - name: Archive apk-x86
        uses: actions/upload-artifact@v2
        with:
          name: exyji-x86_64.apk
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk
          # retention-days: 5
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
