name: Build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '15.0.2'
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    - run: flutter pub get
    # - run: flutter test
    - run: flutter build apk --split-per-abi
    # - run: flutter build ios --release --no-codesign
    - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
          # retention-days: 5